name: Spleef_plugin
version: 1.0.0
main: io.github.danteserrano.Main
api-version: 1.19

commands:
  kit:
    description: Gives kit
    usage: /kit kit_name
  arena:
    description: Teleports to arena
    usage: /arena arena_number

permissions:

